<?php include ("../../../../header.phtml"); ?>
<div class="container klassen">
	<div class="row search">
		<div class="btn-group">
			<input id="searchinput" type="search" class="form-control" placeholder="Klasse Suche">
		 	<i id="searchclear" class="fa fa-times" aria-hidden="true"></i>
		</div>
		<button type="button" class="btn btn-primary active-search">Suchen</button>
		<button type="button" class="btn btn-primary add-class">Klasse Hinzufügen</button>
	</div>
	<div class="row panel-group">

		<div class="panel panel-primary col-xs-3">
			<div class="panel-heading">
				<h3 class="panel-title">FIA 51</h3>
			</div>
			<div class="panel-body">
				Panel content
			</div>
		</div>
		<div class="panel panel-primary col-xs-3">
			<div class="panel-heading">
				<h3 class="panel-title">FIA 51</h3>
			</div>
			<div class="panel-body">
				Panel content
			</div>
		</div>
		<div class="panel panel-primary col-xs-3">
			<div class="panel-heading">
				<h3 class="panel-title">FIA 51</h3>
			</div>
			<div class="panel-body">
				Panel content
			</div>
		</div>
		<div class="panel panel-primary col-xs-3">
			<div class="panel-heading">
				<h3 class="panel-title">FIA 51</h3>
			</div>
			<div class="panel-body">
				Panel content
			</div>
		</div>

	</div>
</div>
<?php include ("../../../../footer.phtml"); ?>
