<?php
	$siteTitle = "Lehrer Übersicht";
	include ("../../../../header.phtml");
?>
<?php
$lastname = "";

if (!isset($_REQUEST['lastname'])) {
	$lastname = $_REQUEST['lastname'];
}

$teacherController = new TeacherController();
$teachers = $teacherController->getEntities($lastname);
?>
<div class="container">
	<div class="row search">
		<div class="btn-group">
			<input id="searchinput" type="search" class="form-control" placeholder="Lehrer Suchen">
		 	<i id="searchclear" class="fa fa-times" aria-hidden="true"></i>
		</div>
		<button class="btn btn-primary active-search">Suchen</button>
		<button class="btn btn-primary add-button">Lehrer Hinzufügen</button>
	</div>
	<div class="row panel-group">
		<?php
			foreach ($teachers as $value) {
		?>
		<div class="col-md-3 col-xs-6">
			<div class="panel panel-primary">
				<div class="panel-body">
					<?=$value["name"]?>
				</div>
				<div class="panel-footer">
					<div class="text">
						<?=$value["short"]?>
					</div>
					<div class="icons">
						<a><i class="fa fa-pencil" aria-hidden="true"></i></a>
						<a><i class="fa fa-times" aria-hidden="true"></i></a>
					</div>
				</div>
			</div>
		</div>

		<?php
			}
		 ?>


	</div>
</div>
<?php include ("../../../../footer.phtml"); ?>
