<?php include ("../../../../header.phtml"); ?>
<?php
$classes = array(
	    0 => array(
	         "name" => "Hans Wurst",
			 "short" => "HW"
	    ),
		1 => array(
			"name" => "Hans Wurst",
			"short" => "HW"
	    ),
		2 => array(
			"name" => "Hans Wurst",
			"short" => "HW"
	    ),
		3 => array(
			"name" => "Hans Wurst",
			"short" => "HW"
	    ),
		4 => array(
			"name" => "Hans Wurst",
			"short" => "HW"
	    ),
		5 => array(
			"name" => "Hans Wurst",
			"short" => "HW"
	    )
	);
?>
<div class="container klassen">
	<div class="row search">
		<div class="btn-group">
			<input id="searchinput" type="search" class="form-control" placeholder="Lehrer Suchen">
		 	<i id="searchclear" class="fa fa-times" aria-hidden="true"></i>
		</div>
		<button type="button" class="btn btn-primary active-search">Suchen</button>
		<button type="button" class="btn btn-primary add-class">Lehrer Hinzufügen</button>
	</div>
	<div class="row panel-group">
		<?php
			foreach ($classes as &$value) {
		?>
		<div class="col-xs-3">
			<div class="panel panel-primary">
				<div class="panel-body">
					<?php echo $value["name"]?>
				</div>
				<div class="panel-footer">
					<div class="text">
						<?php echo $value["short"]?>
					</div>
					<div class="icons">
						<a><i class="fa fa-pencil" aria-hidden="true"></i></a>
						<a><i class="fa fa-times" aria-hidden="true"></i></a>
					</div>
				</div>
			</div>
		</div>

		<?php
			}
		 ?>


	</div>
</div>
<?php include ("../../../../footer.phtml"); ?>
