
<!DOCTYPE html>
<html lang="de">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
	<? include("../../../../src/view/phtml/css-init.phtml") ?>
    <title>GSO - Kalender</title>
</head>

<body>
	<header>
		<nav class="navbar">
			<span class="navbar-brand logo" href="#">
                <img alt="Logo" src="../../../../src/data/media/img/gso-bk-logo.jpg">
			</span>
			<span class="navbar-brand headline">
				Seitentitel
			</span>
			<span class="navbar-brand drop" data-toggle="dropdown">
				<div class="btn-group dropdown">
					<i class="fa fa-bars" aria-hidden="true"></i>

					<div class="dropdown-container dropdown-pull-right">

						<ul class="dropdown-menu">
						  <li><a href="#">HTML</a></li>
						  <li><a href="#">CSS</a></li>
						  <li><a href="#">JavaScript</a></li>
						</ul>


					</div>
				</div>
			<span>
		</nav>
	</header>
	<main>
