<!DOCTYPE html>
<html lang="de">

<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<?php include("../../../../src/view/phtml/css-init.phtml") ?>
	<title>GSO - Kalender</title>
</head>

<body>
	<header>
		<nav class="navbar navbar-default">
			<div class="navbar-header">
				<a href="#">
					<img alt="Logo" src="../../../../src/data/media/img/gso-bk-logo.jpg">
  				</a>
			</div>
			<div class="headline">
				<h3>Seitentitel</h3>
			</div>
			<div class="dropdown">
				<i class="fa fa-bars" aria-hidden="true" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true"></i>
				<ul class="dropdown-menu dropdown-pull-right" aria-labelledby="dropdownMenu1">
					<li><a href="#">Action</a></li>
					<li><a href="#">Another action</a></li>
					<li><a href="#">Something else here</a></li>
					<li><a href="#">Separated link</a></li>
				</ul>
			</div>
		</nav>
	</header>
	<main>
