<?php include ("header.phtml"); ?>
	<div class="container login">
		<div class="row">

			<div class="main">

				<h3>Login</h3>

				<form role="form">
					<div class="form-group">
						<label for="inputUsernameEmail">Benutzernamen</label>
						<input type="text" class="form-control" id="inputUsernameEmail">
					</div>
					<div class="form-group">
						<label for="inputPassword">Passwort</label>
						<input type="password" class="form-control" id="inputPassword">
					</div>
					<button type="submit" class="btn btn btn-primary">
						Log In
					</button>
				</form>

			</div>

		</div>
	</div>
<?php include ("footer.phtml"); ?>
