<?php include("../../../../src/controller/AbstractController.php") ?>
<?php include("../../../../src/controller/ClassController.php") ?>
<?php include("../../../../src/controller/DatabaseController.php") ?>
<?php include("../../../../src/controller/EvaluationSheetController.php") ?>
<?php include("../../../../src/controller/LoginController.php") ?>
<?php include("../../../../src/controller/StudentsController.php") ?>
<?php include("../../../../src/controller/SubjectContentController.php") ?>
<?php include("../../../../src/controller/TeacherController.php") ?>